version: "3"
services:
  wemall_mysql:
    build:
      context: ./
      dockerfile: mysql.Dockerfile
    ports:
      - "3306:3306"
    container_name: wemall_mysql
    privileged: true
    environment:
      - MYSQL_USER=wmall
      - MYSQL_PASSWORD=pEP5c8ekwYMsPY7N
      - MYSQL_DATABASE=wmall
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    restart: always
  wemall_redis:
    restart: always
    container_name: wemall_redis
    image: redis:6.2.6
    ports:
      - 6379:6379
    command: redis-server
  wemall_golang:
    build:
      context: ./
      dockerfile: golang.Dockerfile
    ports:
      - 8012:8012
    container_name: wemall_golang
    privileged: true
    volumes:
      - .:/usr/src/wemall
    depends_on:
      - wemall_redis
      - wemall_mysql
    links:
      - wemall_redis
      - wemall_mysql
    command: go run main.go
    restart: always
  wemall_nodejs_webmall:
    build:
      context: ./
      dockerfile: webmall.Dockerfile
    privileged: true
    volumes:
      - ./webmall/:/usr/src/wemall/webmall
    command: "pm2-runtime src/App.js"
    ports:
      - "3000:3000"
    container_name: wemall_nodejs_webmall
    depends_on:
      - wemall_golang
    links:
      - wemall_golang
  nginx:
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    ports:
      - "8088:80"
    container_name: wemall_nginx
    restart: always
    privileged: true
    links:
      - wemall_golang
      - wemall_nodejs_start
      - wemall_nodejs_static
      - wemall_nodejs_webmall
    depends_on:
      - wemall_golang
      - wemall_nodejs_start
      - wemall_nodejs_static
      - wemall_nodejs_webmall
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
  wemall_nodejs_start:
    build:
      context: ./
      dockerfile: nodejs.Dockerfile
    command: npm start
    privileged: true
    volumes:
      - ./nodejs/:/usr/src/wemall/nodejs
    ports:
      - "8010:8010"
      - "8881:8881"
    container_name: wemall_nodejs_start
    depends_on:
      - wemall_golang
    links:
      - wemall_golang
  wemall_nodejs_static:
    build:
      context: ./
      dockerfile: nodejs.Dockerfile
    command: npm run staticServ
    privileged: true
    ports:
      - 8011:8011
    container_name: wemall_nodejs_static
    volumes:
      - ./nodejs/:/usr/src/wemall/nodejs  
    depends_on:
      - wemall_golang
    links:
      - wemall_golang