version: "3.5"

services:
  nginx:
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    ports:
      - "8088:80"
    container_name: wemall-nginx
    restart: always
    networks:
      - wemall-network

  golang:
    build:
      context: ./
      dockerfile: golang.Dockerfile
    ports:
      - "8012:8012"
    container_name: wemall-golang
    volumes:
      - .:/usr/src/wemall
    depends_on:
      - db
    command: go run ./main.go
    restart: always
    networks:
      - wemall-network

  nodejs-start:
    build:
      context: ./
      dockerfile: nodejs.Dockerfile
    command: npm start
    volumes:
      - ./nodejs/:/usr/src/wemall/nodejs
    ports:
      - "8010:8010"
      - "8881:8881"
    container_name: wemall-nodejs-start
    depends_on:
      - db
    networks:
      - wemall-network

  nodejs-staic:
    build:
      context: ./
      dockerfile: nodejs.Dockerfile
    command: npm run staticServ
    ports:
      - "8011:8011"
    container_name: wemall-nodejs-static
    volumes:
      - ./nodejs/:/usr/src/wemall/nodejs    
    depends_on:
      - db
    networks:
      - wemall-network

  db:
    build:
      context: ./
      dockerfile: mysql.Dockerfile
    ports:
      - "3306:3306"
    container_name: wemall-mysql
    environment:
      - MYSQL_USER=wmall
      - MYSQL_PASSWORD=pEP5c8ekwYMsPY7N
      - MYSQL_DATABASE=wmall
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    restart: always
    volumes:
      - db:/var/lib/mysql
    depends_on:
      - nginx
    networks:
      - wemall-network

volumes:
  db:

networks:
  wemall-network:
    driver: bridge